---
- hosts: localhost
  connection: local
  vars_files:
    - vars/picture-haus.yml
  tasks:
    - name: determine public ip
      shell: "dig +short myip.opendns.com @resolver1.opendns.com"
      register: public_ip_result

    - set_fact:
        public_ip: "{{ public_ip_result.stdout }}"

    - debug: msg="{{ public_ip }}"

    - ec2_group:
        name: "{{ picture_haus_ec2_group }}"
        description: allows SSH and HTTP only
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "{{ public_ip }}/32"
          - proto: tcp
            from_port: 9200
            to_port: 9200
            cidr_ip: "{{ public_ip }}/32"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ public_ip }}/32"
          - proto: tcp
            from_port: 19999
            to_port: 19999
            cidr_ip: "{{ public_ip }}/32"

    - ec2:
        instance_type: m3.large
        image: "{{ picture_haus_ami }}"
        keypair: "{{ lookup('ENV', 'EC2_KEYPAIR') }}"
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: "500"
        exact_count: 1
        wait: yes
        group: "{{ picture_haus_ec2_group }}"
        instance_tags:
          Name: "{{ picture_haus_instance_name }}"
        count_tag:
          Name: "{{ picture_haus_instance_name }}"
      register: instance

    - name: "provision naked DNS"
      route53:
        command: create
        zone: "{{ picture_haus_naked_domain }}"
        record: "{{ picture_haus_naked_domain }}"
        type: A
        ttl: 60
        value: "{{ instance.tagged_instances[0].public_ip }}"
        overwrite: true

    - name: "provision wildcard DNS"
      route53:
        command: create
        zone: "{{ picture_haus_naked_domain }}"
        record: "*.{{ picture_haus_naked_domain }}"
        type: CNAME
        ttl: 60
        value: "{{ picture_haus_naked_domain }}"
        overwrite: true

    - name: "set picture_haus_host"
      set_fact:
        picture_haus_host: "{{ instance.tagged_instances[0].public_ip }}"

    - name: "create picture-haus inventory"
      template: src=templates/inventory.j2 dest=inventory/picture-haus
